In [6]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("cancer_b.csv")
df.head(5)

,Id,Diagnosis,Radius (mean),Texture (mean),Perimeter (mean),Area (mean),Smoothness (mean),Compactness (mean),Concavity (mean),Concave points (mean),...,Radius (worst),Texture (worst),Perimeter (worst),Area (worst),Smoothness (worst),Compactness (worst),Concavity (worst),Concave points (worst),Symmetry (worst),Fractal dimension (worst)
0,8510426,B,13.540,14.36,87.46,566.3,0.09779,0.08129,0.06664,0.047810,...,15.110,19.26,99.70,711.2,0.14400,0.17730,0.23900,0.12880,0.2977,0.07259
1,8510653,B,13.080,15.71,85.63,520.0,0.10750,0.12700,0.04568,0.031100,...,14.500,20.49,96.09,630.5,0.13120,0.27760,0.18900,0.07283,0.3184,0.08183
2,8510824,B,9.504,12.44,60.34,273.9,0.10240,0.06492,0.02956,0.020760,...,10.230,15.66,65.13,314.9,0.13240,0.11480,0.08867,0.06227,0.2450,0.07773
3,854941,A,13.030,18.42,82.61,523.8,0.08983,0.03766,0.02562,0.029230,...,13.300,22.81,84.46,545.9,0.09701,0.04619,0.04833,0.05013,0.1987,0.06169
4,85713702,B,8.196,16.84,51.71,201.9,0.08600,0.05943,0.01588,0.005917,...,8.964,21.96,57.26,242.2,0.12970,0.13570,0.06880,0.02564,0.3105,0.07409

In [8]:
df.describe()

,Id,Radius (mean),Texture (mean),Perimeter (mean),Area (mean),Smoothness (mean),Compactness (mean),Concavity (mean),Concave points (mean),Symmetry (mean),...,Radius (worst),Texture (worst),Perimeter (worst),Area (worst),Smoothness (worst),Compactness (worst),Concavity (worst),Concave points (worst),Symmetry (worst),Fractal dimension (worst)
count,3.570000e+02,357.000000,357.000000,357.000000,357.000000,357.000000,357.000000,357.000000,357.000000,357.000000,...,357.000000,357.000000,357.000000,357.000000,357.000000,357.000000,357.000000,357.000000,357.000000,357.000000
mean,2.654382e+07,12.146524,17.914762,78.075406,462.790196,0.092478,0.080085,0.046058,0.025717,0.174186,...,13.379801,23.515070,87.005938,558.899440,0.124959,0.182673,0.166238,0.074444,0.270246,0.079442
std,1.167397e+08,1.780512,3.995125,11.807438,134.287118,0.013446,0.033750,0.043442,0.015909,0.024807,...,1.981368,5.493955,13.527091,163.601424,0.020013,0.092180,0.140368,0.035797,0.041745,0.013804
min,8.913000e+03,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,...,7.930000,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156600,0.055210
25%,8.746620e+05,11.080000,15.150000,70.870000,378.200000,0.083060,0.055620,0.020310,0.015020,0.158000,...,12.080000,19.580000,78.270000,447.100000,0.110400,0.112000,0.077080,0.051040,0.240600,0.070090
50%,9.089160e+05,12.200000,17.390000,78.180000,458.400000,0.090760,0.075290,0.037090,0.023440,0.171400,...,13.350000,22.820000,86.920000,547.400000,0.125400,0.169800,0.141200,0.074310,0.268700,0.077120
75%,8.812816e+06,13.370000,19.760000,86.100000,551.100000,0.100700,0.097550,0.059990,0.032510,0.189000,...,14.800000,26.510000,96.590000,670.000000,0.137600,0.230200,0.221600,0.097490,0.298300,0.085410
max,9.113205e+08,17.850000,33.810000,114.600000,992.100000,0.163400,0.223900,0.410800,0.085340,0.274300,...,19.820000,41.780000,127.100000,1210.000000,0.200600,0.584900,1.252000,0.175000,0.422800,0.148600

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 357 entries, 0 to 356
Data columns (total 32 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Id                         357 non-null    int64
 1   Diagnosis                  357 non-null    str
 2   Radius (mean)              357 non-null    float64
 3   Texture (mean)             357 non-null    float64
 4   Perimeter (mean)           357 non-null    float64
 5   Area (mean)                357 non-null    float64
 6   Smoothness (mean)          357 non-null    float64
 7   Compactness (mean)         357 non-null    float64
 8   Concavity (mean)           357 non-null    float64
 9   Concave points (mean)      357 non-null    float64
 10  Symmetry (mean)            357 non-null    float64
 11  Fractal dimension (mean)   357 non-null    float64
 12  Radius (se)                357 non-null    float64
 13  Texture (se)               357 non-null    float64
 14  Perimeter (se)             357 non-null    float64
 15  Area (se)                  357 non-null    float64
 16  Smoothness (se)            357 non-null    float64
 17  Compactness (se)           357 non-null    float64
 18  Concavity (se)             357 non-null    float64
 19  Concave points (se)        357 non-null    float64
 20  Symmetry (se)              357 non-null    float64
 21  Fractal dimension (se)     357 non-null    float64
 22  Radius (worst)             357 non-null    float64
 23  Texture (worst)            357 non-null    float64
 24  Perimeter (worst)          357 non-null    float64
 25  Area (worst)               357 non-null    float64
 26  Smoothness (worst)         357 non-null    float64
 27  Compactness (worst)        357 non-null    float64
 28  Concavity (worst)          357 non-null    float64
 29  Concave points (worst)     357 non-null    float64
 30  Symmetry (worst)           357 non-null    float64
 31  Fractal dimension (worst)  357 non-null    float64
dtypes: float64(30), int64(1), str(1)
memory usage: 89.4 KB

In [10]:
df.tail(3)

,Id,Diagnosis,Radius (mean),Texture (mean),Perimeter (mean),Area (mean),Smoothness (mean),Compactness (mean),Concavity (mean),Concave points (mean),...,Radius (worst),Texture (worst),Perimeter (worst),Area (worst),Smoothness (worst),Compactness (worst),Concavity (worst),Concave points (worst),Symmetry (worst),Fractal dimension (worst)
354,925292,B,14.05,27.15,91.38,600.4,0.09929,0.11260,0.04462,0.04304,...,15.300,33.17,100.20,706.7,0.12410,0.22640,0.1326,0.1048,0.2250,0.08321
355,925311,B,11.20,29.37,70.67,386.0,0.07449,0.03558,0.00000,0.00000,...,11.920,38.30,75.19,439.6,0.09267,0.05494,0.0000,0.0000,0.1566,0.05905
356,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [11]:
required_column = df[['Id' ,'Diagnosis','Radius (mean)']]
required_column.head(5)

         Id Diagnosis  Radius (mean)
0   8510426         B         13.540
1   8510653         B         13.080
2   8510824         B          9.504
3    854941         A         13.030
4  85713702         B          8.196

In [12]:
required_column['Diagnosis'].unique()

<StringArray>
['B', 'A']
Length: 2, dtype: str

Identifying IQR

In [ ]:
# numpy to identifying iqr
q1 = np.percentile(required_column['Radius (mean)'] , 25)
q3 = np.percentile(required_column['Radius (mean)'] , 75)
iqr = q3-q1
iqr

np.float64(2.289999999999999)

In [ ]:
#pandas to identifying iqr
q1 = required_column['Radius (mean)'].quantile(0.25)
q3 = required_column['Radius (mean)'].quantile(0.75)
iqr = q3-q1
iqr

np.float64(2.289999999999999)

In [16]:
lower_bound = q1 - 1.5*iqr
upper_bound = q3 + 1.5*iqr
print(lower_bound)
print(upper_bound)

7.645000000000001
16.805

In [18]:
final_radius = required_column[(required_column['Radius (mean)'] >= lower_bound) &(required_column['Radius (mean)'] <= upper_bound)]
final_radius.describe()

                 Id  Radius (mean)
count  3.540000e+02     354.000000
mean   2.648360e+07      12.131746
std    1.171720e+08       1.722440
min    8.913000e+03       7.691000
25%    8.747062e+05      11.092500
50%    9.086925e+05      12.195000
75%    8.812557e+06      13.330000
max    9.113205e+08      16.500000

handling categorical data

In [19]:
required_column.head(5)

         Id Diagnosis  Radius (mean)
0   8510426         B         13.540
1   8510653         B         13.080
2   8510824         B          9.504
3    854941         A         13.030
4  85713702         B          8.196

In [20]:
dict =pd.DataFrame({'Colour' :['Red' ,'green' , 'blue' , 'yellow' ,'purple']})

In [21]:
dict

   Colour
0     Red
1   green
2    blue
3  yellow
4  purple

one hot encoding technique

In [ ]:
encoded_dict = pd.get_dummies(dict,columns=['Colour'], dtype = int)
print(encoded_dict)

   Colour_Red  Colour_blue  Colour_green  Colour_purple  Colour_yellow
0           1            0             0              0              0
1           0            0             1              0              0
2           0            1             0              0              0
3           0            0             0              0              1
4           0            0             0              1              0

In [26]:
enco_dict = pd.get_dummies(required_column, columns=['Diagnosis'] , dtype =int)
print(enco_dict)

           Id  Radius (mean)  Diagnosis_A  Diagnosis_B
0     8510426         13.540            0            1
1     8510653         13.080            0            1
2     8510824          9.504            0            1
3      854941         13.030            1            0
4    85713702          8.196            0            1
..        ...            ...          ...          ...
352    925277         14.590            0            1
353    925291         11.510            0            1
354    925292         14.050            0            1
355    925311         11.200            0            1
356     92751          7.760            0            1

[357 rows x 4 columns]